### ISSUE TITLE
Use Drupal permission system instead of the roles config

### ISSUE THREAD

**Issue by donquixote** [CollaboraOnline/collabora-drupal#27]
(pull request soon...)

**Comment by donquixote** [comment]
@hfiguiere Hi
Could you describe the significance of the `IsAnonymousUser` value sent with the WOPI response?

Currently in this Drupal module, the WOPI controller will return IsAnonymousUser = TRUE if and only if the user is anonymous in Drupal.

What would be the effect of returning the "wrong" value here?

**Comment by hfiguiere** [comment]
Currently it doesn't seem to be used, but there are plans to use it for things like comments. I think it should be carefully set for cases where the user isn't authenticated.
