### ISSUE TITLE
Remove ending `?>` in php files.

### ISSUE THREAD

**Issue by donquixote** [CollaboraOnline/collabora-drupal#33]
Some of the php files have an ending `?>`.
This is unnecessary, goes against all conventions, _and_ it can have an unpleasant side effect if the `?>` is followed by a line break or any kind of whitespace. In that case it can cause the legendary "headers already sent".

So let's remove it.
This will be a simple PR.

**Comment by donquixote** [comment]
> yes. I ran phpcs on a different project and it started complaining.

There is definitely more to fix with phpcs.
And if you run it, you should make sure to use Drupal conventions, which are different from other typical php projects.

The removal of `?>` is a bit different in that it can have a real effect on functionality (usually bad).
I am not sure if a single line break after `?>` is enough to cause problems, or if we would need multiple.
Either way, removing it is the right thing to do.

And I think it's ok to do this in a separate PR, separate from aesthetic code style fixes.

**Comment by hfiguiere** [comment]
definitely.
