### ISSUE TITLE
Avoid hard-coded module path in template

### ISSUE THREAD

**Issue by donquixote** [CollaboraOnline/collabora-drupal#35]
The `templates/collabora-online-full.html.twig` template contains hard-coded paths in the urls to js and css files.
```twig
  <head>
    <script src="/modules/contrib/collabora_online/js/cool.js"></script>
    <link href="/modules/contrib/collabora_online/css/cool.css" rel="stylesheet" />
  </head>
```

This assumes that the module is in `/modules/contrib/collabora_online`, which is not guaranteed.
It also assumes that the base url is just `/`, which means Drupal is not installed in a subdirectory.

Instead, these urls should be composed from variables passed into the template.

**Comment by donquixote** [comment]
Also interesting: We are adding the library, via `'#attached'`, but it does not really work, because we are not using a regular page html template that would be populated with the assets.

There is an example in Drupal core which uses a placeholder mechanism for assets in an iframe content.
https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/media/src/Controller/OEmbedIframeController.php?ref_type=heads#L176
https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/media/templates/media-oembed-iframe.html.twig?ref_type=heads

This same technique is used in the main `html.html.twig` which is used on regular pages.
https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/system/templates/html.html.twig?ref_type=heads#L31

We could use the same technique, but for now I would prefer to do something simpler, and simply pass the module path as a variable.

**Comment by hfiguiere** [comment]
I was having trouble with making it work with the library so I took that bad shortcut, and kinda forgot about it, even after fixing it once.
