### ISSUE TITLE
Support: Is the email needed in UserExtraInfo?

### ISSUE THREAD

**Issue by donquixote** [CollaboraOnline/collabora-drupal#80]
Hello @hfiguiere 
In `WopiController::wopiCheckFileInfo()` we are sending the user email address as part of `UserExtraInfo` with the response payload.

We would like to know if this is needed somehow.
For privacy reasons, we want to send only the data that is needed.

Thanks!

**Comment by hfiguiere** [comment]
I don't see where it is used. It's just in the sdk documentation, and was added probably without thinking.

So it possibly can be removed without side effect.

The `avatar` is used though. While it is safe to remove it, it is nice to have. Could be configurable if people have privacy concerns.

**Comment by donquixote** [comment]
Alright, good to know, thanks!
